on:
  pull_request:
    branches: [ main ]

permissions:
  checks: write        # ✅ Needed for test summary
  pull-requests: write # Optional, allows commenting if needed
  contents: read
    
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Run Tests
      run: dotnet test --no-build --configuration Release --logger "trx;LogFileName=test-results.trx"
      env:
        ASPNETCORE_ENVIRONMENT: Production
        ConnectionStrings__DefaultConnection: "server=localhost;port=3306;database=testdb;user=root;password=password"

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: '**/test-results.trx'

    - name: Report test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Unit Tests
        path: '**/test-results.trx'
        reporter: dotnet-trx
        fail-on-error: false
        output: check-run
